### PR TITLE
add lambdalisue/deno-unknownutil

### PR DESCRIPTION
**Pull request by ryoppippi**
I ran the benchmark on my machine and confirmed that it works fine

chart: https://image-charts.com/chart.js/2.8.0?bkg=white&c=%7B%22type%22%3A%22bar%22%2C%22data%22%3A%7B%22labels%22%3A%5B%22validator.js%22%2C%22validate.js%22%2C%22validatorjs%22%2C%22joi%22%2C%22ajv%22%2C%22mschema%22%2C%22parambulator%22%2C%22fastest-validator%22%2C%22yup%22%2C%22nope%22%2C%22jsvalidator%22%2C%22Valibot%22%2C%22Zod%22%2C%22unknownutil%22%5D%2C%22datasets%22%3A%5B%7B%22label%22%3A%22Dataset%201%22%2C%22backgroundColor%22%3A%22rgba%2854%2C%20162%2C%20235%2C%200.5%29%22%2C%22borderColor%22%3A%22rgb%2854%2C%20162%2C%20235%29%22%2C%22borderWidth%22%3A1%2C%22data%22%3A%5B773160.149934184%2C477414.8754836563%2C354362.43758161634%2C431581.8159907141%2C9232596.078371763%2C1125233.475695902%2C53198.565408911236%2C9161083.782176802%2C65920.97887459854%2C3184590.578707232%2C1248201.5533458265%2C3523994.2016820638%2C1714611.6164937017%2C12087656.057532521%5D%7D%5D%7D%2C%22options%22%3A%7B%22responsive%22%3Afalse%2C%22legend%22%3A%7B%22display%22%3Afalse%2C%22position%22%3A%22top%22%7D%2C%22title%22%3A%7B%22display%22%3Atrue%2C%22text%22%3A%22Simple%20object%7C%28ops%2Fsec%29%22%7D%2C%22layout%22%3A%7B%22padding%22%3A20%7D%7D%7D

```sh

========================
  Validators benchmark
========================

Platform info:
==============
   Darwin 22.6.0 arm64
   Node.JS: 20.8.0
   V8: 11.3.244.8-node.16
   CPU: Apple M1 × 8
   Memory: 16 GB

Suite: Simple object
====================

✔ validator.js            773,160 ops/sec
✔ validate.js             477,415 ops/sec
✔ validatorjs             354,362 ops/sec
✔ joi                     431,582 ops/sec
✔ ajv                   9,232,596 ops/sec
✔ mschema               1,125,233 ops/sec
✔ parambulator             53,199 ops/sec
✔ fastest-validator     9,161,084 ops/sec
✔ yup                      65,921 ops/sec
✔ nope                  3,184,591 ops/sec
✔ jsvalidator           1,248,202 ops/sec
✔ Valibot               3,523,994 ops/sec
✔ Zod                   1,714,612 ops/sec
✔ unknownutil          12,087,656 ops/sec

   validator.js             -93.6%    (773,160 ops/sec)   (avg: 1μs)
   validate.js             -96.05%    (477,415 ops/sec)   (avg: 2μs)
   validatorjs             -97.07%    (354,362 ops/sec)   (avg: 2μs)
   joi                     -96.43%    (431,582 ops/sec)   (avg: 2μs)
   ajv                     -23.62%   (9,232,596 ops/sec)   (avg: 108ns)
   mschema                 -90.69%   (1,125,233 ops/sec)   (avg: 888ns)
   parambulator            -99.56%     (53,199 ops/sec)   (avg: 18μs)
   fastest-validator       -24.21%   (9,161,084 ops/sec)   (avg: 109ns)
   yup                     -99.45%     (65,921 ops/sec)   (avg: 15μs)
   nope                    -73.65%   (3,184,591 ops/sec)   (avg: 314ns)
   jsvalidator             -89.67%   (1,248,202 ops/sec)   (avg: 801ns)
   Valibot                 -70.85%   (3,523,994 ops/sec)   (avg: 283ns)
   Zod                     -85.82%   (1,714,612 ops/sec)   (avg: 583ns)
   unknownutil                  0%   (12,087,656 ops/sec)   (avg: 82ns)

┌───────────────────┬────────────────────────────────────────────────────┐
│ validator.js      │ ███                                                │
├───────────────────┼────────────────────────────────────────────────────┤
│ validate.js       │ ██                                                 │
├───────────────────┼────────────────────────────────────────────────────┤
│ validatorjs       │ █                                                  │
├───────────────────┼────────────────────────────────────────────────────┤
│ joi               │ ██                                                 │
├───────────────────┼────────────────────────────────────────────────────┤
│ ajv               │ ██████████████████████████████████████             │
├───────────────────┼────────────────────────────────────────────────────┤
│ mschema           │ █████                                              │
├───────────────────┼────────────────────────────────────────────────────┤
│ parambulator      │                                                    │
├───────────────────┼────────────────────────────────────────────────────┤
│ fastest-validator │ ██████████████████████████████████████             │
├───────────────────┼────────────────────────────────────────────────────┤
│ yup               │                                                    │
├───────────────────┼────────────────────────────────────────────────────┤
│ nope              │ █████████████                                      │
├───────────────────┼────────────────────────────────────────────────────┤
│ jsvalidator       │ █████                                              │
├───────────────────┼────────────────────────────────────────────────────┤
│ Valibot           │ ███████████████                                    │
├───────────────────┼────────────────────────────────────────────────────┤
│ Zod               │ ███████                                            │
├───────────────────┼────────────────────────────────────────────────────┤
│ unknownutil       │ ██████████████████████████████████████████████████ │
└───────────────────┴────────────────────────────────────────────────────┘

Chart: https://image-charts.com/chart.js/2.8.0?bkg=white&c=%7B%22type%22%3A%22bar%22%2C%22data%22%3A%7B%22labels%22%3A%5B%22validator.js%22%2C%22validate.js%22%2C%22validatorjs%22%2C%22joi%22%2C%22ajv%22%2C%22mschema%22%2C%22parambulator%22%2C%22fastest-validator%22%2C%22yup%22%2C%22nope%22%2C%22jsvalidator%22%2C%22Valibot%22%2C%22Zod%22%2C%22unknownutil%22%5D%2C%22datasets%22%3A%5B%7B%22label%22%3A%22Dataset%201%22%2C%22backgroundColor%22%3A%22rgba%2854%2C%20162%2C%20235%2C%200.5%29%22%2C%22borderColor%22%3A%22rgb%2854%2C%20162%2C%20235%29%22%2C%22borderWidth%22%3A1%2C%22data%22%3A%5B773160.149934184%2C477414.8754836563%2C354362.43758161634%2C431581.8159907141%2C9232596.078371763%2C1125233.475695902%2C53198.565408911236%2C9161083.782176802%2C65920.97887459854%2C3184590.578707232%2C1248201.5533458265%2C3523994.2016820638%2C1714611.6164937017%2C12087656.057532521%5D%7D%5D%7D%2C%22options%22%3A%7B%22responsive%22%3Afalse%2C%22legend%22%3A%7B%22display%22%3Afalse%2C%22position%22%3A%22top%22%7D%2C%22title%22%3A%7B%22display%22%3Atrue%2C%22text%22%3A%22Simple%20object%7C%28ops%2Fsec%29%22%7D%2C%22layout%22%3A%7B%22padding%22%3A20%7D%7D%7D
```

### CODE REVIEW

**Comment by lambdalisue** [comment]
Well, my unknownutil is not a data validator but rather a type validator, so I feel it's somewhat unfair to include it in benchmarks without annotations or some form of clarification.

**Comment by lambdalisue** [comment]
Please note that I believe it's a good idea to include it in the list. Some people, like myself, require a type validator rather than a data validator, and the benchmark results demonstrate that a type validator is significantly faster and lighter.

**Comment by ryoppippi** [comment]
?

**Comment by icebob** [comment]
While it is not a real value validator like others it's not relevant for this benchmark.

**Pull request closed without merging**
